name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for sh file
      run: chmod +x ./build.sh

    - name: Run build script
      run: ./build.sh

    - name: Run tests
      run: mvn test
