name: Java CI with Maven

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Use Java 11
        distribution: 'temurin'

    - name: Grant execute permission for build script
      run: chmod +x ./build.sh

    - name: Build with Maven
      run: mvn clean package  # Adjust Maven command as needed

    - name: Run tests
      run: mvn test  # Run Maven tests

    # Add additional steps for deployment, etc., if needed
